//! Markdown reporting for the cache observatory.
//!
//! One report per run, written to stdout (and intended to be redirected to
//! `docs/observatory/cache-baseline.md`). Each report opens with a hardware
//! fingerprint sourced from `/proc/cpuinfo` and `/sys/devices/system/cpu/`
//! so future runs on other hosts produce comparable, attributable data.

use std::fmt::Write;
use std::fs;

use crate::workloads::Report;

/// Concatenates the full markdown report (hardware fingerprint + every
/// workload table) into a string ready for stdout or a file.
pub fn render(reports: &[Report]) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# cache-observatory baseline\n\n\
         Generated by `cargo run --release -p cache-observatory`. Re-run on \
         every dev host; commit results to `docs/observatory/cache-baseline.md` \
         alongside the existing history."
    );
    out.push_str("\n## Host\n\n");
    out.push_str(&render_host());
    for r in reports {
        out.push('\n');
        out.push_str(&render_report(r));
    }
    out
}

fn render_report(r: &Report) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "## {}\n", r.name);
    let _ = writeln!(out, "{}\n", r.description);
    out.push_str(
        "| working-set | elements | ns/element | L1d miss | L2 miss | LLC miss | cycles | inst |\n",
    );
    out.push_str("| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n");
    for s in &r.samples {
        let _ = writeln!(
            out,
            "| {} | {} | {:.2} | {} | {} | {} | {} | {} |",
            human_bytes(s.bytes),
            s.elements,
            s.ns_per_element(),
            opt_u64(s.perf.l1d_misses),
            opt_u64(s.perf.l2_misses),
            opt_u64(s.perf.llc_misses),
            opt_u64(s.perf.cycles),
            opt_u64(s.perf.instructions),
        );
    }
    out
}

fn human_bytes(b: usize) -> String {
    const KIB: usize = 1024;
    const MIB: usize = KIB * 1024;
    if b >= MIB {
        format!("{} MiB", b / MIB)
    } else if b >= KIB {
        format!("{} KiB", b / KIB)
    } else {
        format!("{} B", b)
    }
}

fn opt_u64(v: Option<u64>) -> String {
    match v {
        Some(n) => format!("{n}"),
        None => "—".into(),
    }
}

/// Tries to read `/proc/cpuinfo` and the per-CPU cache descriptors. Missing
/// files degrade gracefully — a future macOS / Windows fingerprint will hook
/// in here.
fn render_host() -> String {
    let mut out = String::new();
    if let Some(model) = read_cpu_model() {
        let _ = writeln!(out, "- **CPU**: {model}");
    }
    for level in &[1u32, 2, 3] {
        if let Some(size) = read_cache_size(*level) {
            let _ = writeln!(out, "- **L{level} cache**: {size}");
        }
    }
    if out.is_empty() {
        out.push_str("- _hardware fingerprint unavailable on this host_\n");
    }
    out
}

fn read_cpu_model() -> Option<String> {
    let text = fs::read_to_string("/proc/cpuinfo").ok()?;
    for line in text.lines() {
        if let Some((k, v)) = line.split_once(':')
            && k.trim() == "model name"
        {
            return Some(v.trim().to_string());
        }
    }
    None
}

fn read_cache_size(level: u32) -> Option<String> {
    // /sys/devices/system/cpu/cpu0/cache/indexN/{level,size,type}
    for idx in 0..8 {
        let base = format!("/sys/devices/system/cpu/cpu0/cache/index{idx}");
        let lvl = fs::read_to_string(format!("{base}/level"))
            .ok()
            .map(|s| s.trim().to_string());
        let ty = fs::read_to_string(format!("{base}/type"))
            .ok()
            .map(|s| s.trim().to_string());
        let size = fs::read_to_string(format!("{base}/size"))
            .ok()
            .map(|s| s.trim().to_string());
        if let (Some(l), Some(t), Some(s)) = (lvl, ty, size) {
            // Prefer the unified or data cache at each level (skip the
            // separate instruction caches).
            if l == level.to_string() && (t == "Data" || t == "Unified") {
                return Some(format!("{s} ({t})"));
            }
        }
    }
    None
}
